HashSyntax:
  EnforcedStyle: hash_rockets

LineLength:
  Max: 186 # TODO: reduce to 80

MethodLength:
  Max: 155 # TODO: reduce to 10

ClassLength:
  Max: 260 # TODO: reduce to 100

BlockNesting:
  Max: 4 # TODO: reduce to 3

CyclomaticComplexity:
  Enabled: false # TODO: enable

Documentation:
  Enabled: false # TODO: enable

NumericLiterals:
  MinDigits: 6
